### ISSUE TITLE
Delete node_modules folder

### ISSUE THREAD

**Issue by ecasilla** [JMHill/shopping-list#1]
Dont forget to delete this for your git tracking history there's no need to have this in GitHub since you have a package json file with all your dependencies use this command in the project folder
git rm --cached -r node_modules/
Then just rm -rf  node_modules/
And git add etc...

**Comment by JMHill** [comment]
Thanks for the tip Ernie - removed node_modules and added the Node.gitignore template from github/gitignore to prevent it from being tracked in the future.
